version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db_auth:
    image: postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  db_payment:
    image: postgres
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  auth_service:
    build:
      context: .
      dockerfile: ./apps/auth-microservice/Dockerfile
    depends_on:
      - kafka
      - db_auth

  payment_service:
    build:
      context: .
      dockerfile: ./apps/payments-microservice/Dockerfile
    depends_on:
      - kafka
      - db_payment

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    depends_on:
      - auth_service
      - payment_service
    ports:
      - "4000:4000"
